apiVersion: v1
kind: Service
metadata:
  name: microservice-svc
  namespace: dev
  labels: 
    app: microservice
spec:
  type: ClusterIP
  selector:
    app: microservice
  ports:
    - name: http
      port: 1000
      targetPort: 8080